// Build script for Vercel deployment
// Generates firebase-config.js from environment variables

const fs = require('fs');
const path = require('path');

const config = {
  apiKey:            process.env.FIREBASE_API_KEY            || "MISSING",
  authDomain:        process.env.FIREBASE_AUTH_DOMAIN        || "MISSING",
  projectId:         process.env.FIREBASE_PROJECT_ID         || "MISSING",
  storageBucket:     process.env.FIREBASE_STORAGE_BUCKET     || "MISSING",
  messagingSenderId: process.env.FIREBASE_MESSAGING_ID       || "MISSING",
  appId:             process.env.FIREBASE_APP_ID             || "MISSING",
  measurementId:     process.env.FIREBASE_MEASUREMENT_ID     || ""
};

const output = `// Auto-generated by build.js — do not edit manually
const firebaseConfig = ${JSON.stringify(config, null, 2)};
window.__SPORTFIT_CONFIG__ = firebaseConfig;
`;

const outPath = path.join(__dirname, 'frontend', 'js', 'firebase-config.js');
fs.writeFileSync(outPath, output);
console.log('✅ firebase-config.js generated from env vars');
